# Generated by Django 3.1.7 on 2021-03-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210308_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(help_text='작가 고유번호', primary_key=True, serialize=False, verbose_name='작가번호'),
        ),
    ]
