# Generated by Django 3.1.7 on 2021-03-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210323_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': '책인스턴스', 'verbose_name_plural': '책인스턴스'},
        ),
    ]
